databases:
  - name: teaching-practice-db
    plan: free
    databaseName: teaching_practice_showcase
    user: teaching_user

services:
  - type: web
    name: teaching-practice-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teaching-practice-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false